on: [push]

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: python3 simple/test.py
      - uses: actions/checkout@v2
        with:
          repository: Photon94/msu-tasks-tests
          token: ${{ secrets.TESTS_TOKEN }}
          path: msu-tasks-tests
      - run: |
          cp "msu-tasks-tests/simple/test.py" "simple/test.py"
          python3 simple/test.py


